### ISSUE TITLE
Including the children based on depth

### ISSUE THREAD

**Issue by AlexVPopov** [mceachen/closure_tree#142]
I have a `Tag` model. In my controller I need to find the current tag and include all its children and sub-children. So if the tag has only one generation, this works:

``` ruby
Tag.includes(:children).find(tag_id)
```

If the tag has two generations, this works:

``` ruby
Tag.includes(children: :children).find(tag_id)
```

However, I need a way of dynamically loading the tag's descendants, based on the number of generations. Here `self_and_descendants` doesn't work, because it just returns an array, omitting the relationships between the descendant tags. What's more, calling `children` on a descendant tag would trigger a db call and not use the info from `self_and_descendants`.

So the first obstacle I came across was that I didn't know how many generations a tag has. I ended up checking depth like this:

``` ruby
depth = Tag.find(tag_id).leaves.last.depth
```

This trigger 3 DB calls. Based on the depth, I construct and evaluate a string of the included children. My final code:

``` ruby
def included_children(tag_id)
  depth = Tag.find(tag_id).leaves.last.depth
  eval(includes_string(depth))
end

def includes_string(depth)
  "{children: #{depth > 1 ? includes_string(depth - 1) : ':children'}}"
end
```

and

``` ruby
Tag.includes(included_children(tag_id)).find(tag_id)
```

This is totally inefficient and not elegant, but I couldn't think of a better way. Are there any capabilities of `closure_tree` that I am missing, with the help of which I can tackle the problem better?

**Comment by CicholGricenchos** [comment]
Maybe you can try to define them as associations:

```ruby
has_one :grand_parent, class_name: 'Catalog', through: :grand_parent_hierarchy, source: :ancestor
has_one :grand_parent_hierarchy, ->{ where(generations: 2) }, class_name: 'CatalogHierarchy', foreign_key: :descendant_id
```
