### ISSUE TITLE
use with polymorphic association

### ISSUE THREAD

**Issue by birarda** [mceachen/closure_tree#143]
We have a model 'Place' and a model 'Domain'.

Each 'Place' has a 'parent_id' and a 'parent_type'. A place can have a domain ID and 'parent_type' will be 'Domain'. closure_tree correctly detects this as the root (because it has a nil parent_id) in that case.

Unfortunately, if I grab a place and ask for its root, the generated SQL assumes it can only be looking for a place, which means it returns nil for the 'root'. Is there an option I can pass to 'closure_tree' to make this work, or should I just add a 'root_domain' has_one to the 'Place' model that uses the same SQL but checks for a domain with that ID?

The currently generated SQL that returns nil is 

```
SELECT  "places".* FROM "places" 
INNER JOIN "place_hierarchies" ON "places"."id" = "place_hierarchies"."ancestor_id" 
WHERE "place_hierarchies"."descendant_id" = $1 AND "places"."pointee_id" IS NULL  
ORDER BY "place_hierarchies".generations asc 
LIMIT 1  [["descendant_id", "e9a6ea94-a4e8-4118-a919-cfcef116dc30"]]
```

**Comment by seuros** [comment]
This look like a nonorthodox use of CT. Could you provide a sample app that reproduce the bug ?

**Comment by birarda** [comment]
Definitely non-orthodox, and not a bug in CT at all. I just wanted to know if you thought there might be a cleaner way than adding my own has_one through

**Comment by mceachen** [comment]
Yeah, nope, there isn't multi table polymorphism support in `closure_tree`. Only STI.
