### ISSUE TITLE
Tree inside tree

### ISSUE THREAD

**Issue by onemanstartup** [mceachen/closure_tree#150]
I have sti model with multiple types.
I want to create multiple trees and then insert them inside another. Is it possible then to ask for full tree with childrens? Like this.
```ruby
MainTree.hash_tree # or custom_hash_tree
```
And get back tree with items as my sti model types? If so would it be performant? 
I'm sorry if it just design question, I just don't know how to realize, searching for solutions.
Thanks.

**Comment by mceachen** [comment]
The readme talks about moving trees into trees. Just add the top node of
the subtree as a child node to the new tree, and things will just work.
There are reparenting tests if you want sample code.
