### ISSUE TITLE
ActiveModel::MassAssignmentSecurity::Error in Rails 4.2.1

### ISSUE THREAD

**Issue by tbrammar** [mceachen/closure_tree#156]
We have a `Tag` model with `has_closure_tree` and are trying to create records

`````
2.1.5 :001 > Tag.create(name: 'Grandpa')
   (0.5ms)  BEGIN
  Tag Exists (1.3ms)  SELECT  1 AS one FROM "tags" WHERE "tags"."token" = $1 LIMIT 1  [["token", "9b52"]]
  SQL (0.9ms)  INSERT INTO "tags" ("name", "token", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["name", "Grandpa"], ["token", "9b52"], ["created_at", "2015-06-01 13:44:50.559933"], ["updated_at", "2015-06-01 13:44:50.559933"]]
   (0.7ms)  SELECT pg_try_advisory_lock(1814493058,0) AS ta04b3ce0fea05bd032f8b54a95ebadae
   (0.4ms)  SELECT pg_advisory_unlock(1814493058,0) AS t407ea30ef4991b612dde23167ff09488
   (0.4ms)  ROLLBACK
ActiveModel::MassAssignmentSecurity::Error: Can't mass-assign protected attributes for TagHierarchy: ancestor, descendant, generations
`````

closure_tree 5.2.0
rails 4.2.1
activerecord 4.2.1
ruby 2.1.5

**Comment by mceachen** [comment]
This issue's been raised and resolved several times, please search prior
issues for context and solutions.

If not, please include your tag model class or a test case that reproduces
this issue.

**Comment by tbrammar** [comment]
RTFM Tom!:

`Make sure you add has_closure_tree after attr_accessible and self.table_name = lines in your model.`

Sorry Matthew

**Comment by mceachen** [comment]
Great to have an easy fix!

Feel free to add more error messages or whatever you think would make the
FM be more "R"able—pull requests are welcomed.
