### ISSUE TITLE
Question: indirect children

### ISSUE THREAD

**Issue by fernandoluizao** [mceachen/closure_tree#158]
I have the following structure:

```
items
   id
   description

items_children
   item_id
   quantity
```

My tables are not self referential, that is, to get the children I need an intermediate table to determine the quantity of each child.

Can I use closure_tree in this scenario? I just need an efficient way to grab all the children of a particular item/collection of items. Any thoughts?

**Comment by mceachen** [comment]
No. Your model needs to have a parent fk column.
