### ISSUE TITLE
HTML Select Box with complete tree

### ISSUE THREAD

**Issue by nazarhussain** [mceachen/closure_tree#163]
HI,

I have structure build closure_tree which is similar to

- General
- PHP
---Frameworks
------Laravel
- Ruby

I need to populate select box with above hierarchy I used this code to try: 

```ruby
Category.all.map { |c| ['- ' * c.depth + c.title, c.id] }
```

It is showing categories with wrong hierarchy. Can any one help me?

**Comment by dmitry** [comment]
@nazarhussain more details please :)

**Comment by nazarhussain** [comment]
I used below code to to get the categories tree in right order 

```ruby
  def options_for_categories_dropdown categories = Category.hash_tree, options=[]
    return @cached_options if @cached_options.present?
    options ||= []
    categories.each do |category, children|
      options << ['- ' * category.depth + category.title, category.id]
      options_for_categories_dropdown(children, options) if children.present?
    end
    options
  end
```

Looks like `has_tree` is the only way to get closure_item items in the right order.
