### ISSUE TITLE
add_child adds a child even if the child fails validation

### ISSUE THREAD

**Issue by rcanand** [mceachen/closure_tree#165]
```ruby
class Post
  validate do |post|
     if post.parent && post.cannot_be_a_child
        post.errors[:base] << "A post cannot be a child if cannot_be_a_child is set to true"
     end
  end
  acts_as_tree
end

parent_post = Post.create!
child_post = Post.create!(cannot_be_a_child:true)
child_post.parent 
#=> nil

parent_post.add_child child_post 
#=> returns new child with parent set

child_post.errors
#=> error from validation...

child_post.parent
#=> points to parent_post

parent_post.children.include? child_post 
#=> true

```
Expected: `add_child` should not add the child if validation fails on `child.save`. 
Even better: there should be an `add_child!` that bubbles up the validation error to the user

**Comment by seuros** [comment]
if you reload the model the child will not be there.

:+1:  in adding `add_child!`, can you submit a PR ?

**Comment by rcanand** [comment]
Reloading fixed it. I investigated the pattern a bit more, and add_child! doesn't make sense, since even the ActiveRecord collections seem to behave like add_child (and do not bubble up the error). Closing.
