### ISSUE TITLE
When parent_id is nil, tag.siblings returns all the instances of the model

### ISSUE THREAD

**Issue by rcanand** [mceachen/closure_tree#166]
```ruby
class Tag <ActiveRecord::Base
   acts_as_tree
end

t1 = Tag.create! #=> <Tag id:1 ...>
t1.siblings #=> <ActiveRecord::Relation []>
t2 = Tag.create!
t2.parent #=> nil
t2.siblings #=> <ActiveRecord::Relation [Tag id:1 ...]>
```
Expected: t2.siblings should return an empty AR:Relation array

**Comment by mceachen** [comment]
You're creating two root nodes here, so t1 would be the expected result
from t2.siblings.

**Comment by rcanand** [comment]
Ok, thanks. I misunderstood that only nodes with the same non-nil parents were returned with siblings.
