### ISSUE TITLE
parent exists, but ancestors is empty

### ISSUE THREAD

**Issue by rcanand** [mceachen/closure_tree#167]
Even though a tag has a parent, tag.ancestors returns empty.

```rb
> tag.parent
#<Tag id: 52770, ...>
> tag.ancestors.count
0
> tag.reload
#<Tag id: 52771, parent_id: 52770, ...>
> tag.ancestors.count
0
```

(on rails 4.2.1)

This doesn't always happen (I have used closure_tree in other projects and they worked fine), but I wonder how it is ever possible that the ancestors are empty when parent is valid, even after calling reload.

**Comment by mceachen** [comment]
Turn on SQL debugging to see what queries are being done, but I suspect
your closure table has gotten corrupted somehow. First try calling .rebuild.

**Comment by rcanand** [comment]
Thanks. Running rebuild! fixed it for now, but I'm not sure what is causing it - looking at sql logs, is it normal to insert a record in the hierarchies table with ascendant_id == descendant_id?

**Comment by mceachen** [comment]
Yes—it makes self_and_* queries much simpler.

**Comment by rcanand** [comment]
`child_tag = tag.children.create!` seems to be the line after which `child_tag.ancestors` is empty. Calling `Tag.rebuild!` after that shows the right `ancestors`.

**Comment by mceachen** [comment]
Fwiw, you shouldn't call rebuild normally—it's quite expensive.

Simple child additions are very well tested and used in this library, so
there's probably something going on with validations or something else that
is preventing normal persistence to succeed. I'd try a new rails app, copy
just the model and no extraneous pre or post save hooks, and see if it
still has problems.

**Comment by rcanand** [comment]
Ok, found the culprit - I was setting a field on the record and saving in after_create. It turns out `after_create` does not guarantee that id is available - using `after_commit :do_method, on: :create` removed the problem. Closing this issue.
