### ISSUE TITLE
Incorrect `root?` value after save

### ISSUE THREAD

**Issue by j15e** [mceachen/closure_tree#176]
It seems the `root?` method incorrectly returns `true` after a model was updated/saved.

I will try to provide more details when possible.

I am working on running the specs, but it's not very straightforward as I am not using rbenv and it seems there is some issue with rails edge gemspec.

**Comment by j15e** [comment]
Update: doing `model.reload` after a save or update fix the issue (more of a workaround).

**Comment by mceachen** [comment]
There are tests for `root?` before and after save, so without a worked example, I'm closing this.
