### ISSUE TITLE
Does not work with ActiveModel::Validator

### ISSUE THREAD

**Issue by martin-schmidt** [mceachen/closure_tree#184]
```ruby
class Klass < ActiveRecord::Base
  has_closure_tree
  validates_with KlassValidator
end
```
```ruby
class KlassValidator < ActiveModel::Validator
  def validate(record)
    record.errors[:base].push 'Record not ok!' unless record_ok? record
  end

  private
  def record_ok? record
    # doing stuff with record.self_and_ancestors but record.self_and_ancestors is an empty Array at this point.
    ...
    return record
  end
end
```
----

    > klass = Klass.find_or_create_by_path(['something'])
     ActiveRecord::RecordInvalid: Validation failed: Record not ok!
    > klass
    => nil

----

**Comment by cvincent** [comment]
I'm having a similar issue where `self_and_ancestors` is empty during a `before_save` callback, even though `parent` is set correctly.

**Comment by mceachen** [comment]
Ancestor and descendant calls can't work if the record isn't persisted.
