### ISSUE TITLE
Ability to use with Ruby 2.0.0

### ISSUE THREAD

**Issue by anduong** [mceachen/closure_tree#186]
Hi team,

Can we downgrade 
```Ruby
gem.required_ruby_version = '>= 2.1.0'
```
in .gemspec file to 
```Ruby
gem.required_ruby_version = '>= 2.0.0'
```
if closure_tree can still work well with Ruby 2.0.0? I think it would help more projects which are still playing with Ruby 2.0.0 like me.

Thanks!

**Comment by mceachen** [comment]
Let's at least run the tests with 2.0.0 and see if they pass. It's been a
long while since I've used 2.0.

Out of curiosity, why not upgrade to 2.1 or 2.2? You may be pleasantly
surprised with the performance boost, and compatibility shouldn't be an
issue.

**Comment by anduong** [comment]
@mceachen Thanks for your prompt reply. 
We are running an e-commerce system. As a law of market, we are stepping into the hottest shopping season of the year in Singapore so any upgrades or changes are risky and may affect badly our revenue.

We have a plan to upgrade to latest Ruby version but it's not the time now :)

Thanks.

**Comment by mceachen** [comment]
Thanks for the PR!
