### ISSUE TITLE
Add support for ordering by string and timestamp

### ISSUE THREAD

**Issue by acaron** [mceachen/closure_tree#189]
Right now, you can only have an integer column. It fails when doing the `node_score` since it is trying to add + 1: `node_score = "(1 + anc.#{_ct.quoted_order_column(false)})` in https://github.com/mceachen/closure_tree/blob/master/lib/closure_tree/numeric_deterministic_ordering.rb

**Comment by acaron** [comment]
For timestamp, apply a simple cast like this (only a working example): `node_score = "(1 + cast(extract(epoch from anc.#{_ct.quoted_order_column(false)}) as integer)) * " +` (postgresql)

For string, a breadcrumb must be create and order by it (a padding of letter "z" can be add so all the string have the same length). See: https://www.percona.com/blog/2011/02/14/moving-subtrees-in-closure-table/#li-comment-947107

**Comment by mceachen** [comment]
Pull requests are welcome! I'll reopen this if you submit a PR.
