### ISSUE TITLE
How to sort children differently?

### ISSUE THREAD

**Issue by AmitJoki** [mceachen/closure_tree#191]
I maintain a separate column say `votes` for each comment. Now, I have only 1 level nesting enabled. 
How would I sort parents based on `votes` and their respective children on `votes`?

Supposing, this is my data:
```
parent1 votes 1
    children votes 1
    children votes 2
    children votes 3
parent2 votes 5
    children votes 1
    children votes 5
    children votes 3
```

I'd want to order like this:
```
parent2 votes 5
    children votes 5
    children votes 3
    children votes 1
parent2 votes 1
    children votes 3
    children votes 2
    children votes 1
```

**Comment by chumakoff** [comment]
+1

**Comment by seuros** [comment]
add a votes_count cache counter, and use it to order.
