### ISSUE TITLE
active_record-acts_as and closure_tree

### ISSUE THREAD

**Issue by thooams** [mceachen/closure_tree#193]
I'd like to use multiple-table-inheritance  (MTI) with closure_tree.

```
Folder #=> #<Folder id: nil>
Item   #=> #<Item id: nil, name: nil, quantity: 1.0, user_id: nil, parent_id: nil, comments: nil, active: true,  actable_id: nil, actable_type: nil, created_at: nil, updated_at: nil>
```
I create a folder and i have this result: 
```
@folder = Folder.first
@folder           #=> #<Folder id: 1>
@folder.acting_as #=> #<Item id: 6, name: "My folder", quantity: 1.0, parent_id: nil .... actable_id: 1, actable_type: 'Folder' >
```

So when i write:
```
@folder    = Folder.create!(name: 'My folder')
@subfolder = @folder.folders.create!(name: 'my subfolder')
```
My parent_id in my subfolder is the **folder** object id and not the **item** object id.
How can i force insert parent_id with the **item** object id ?
Where is the method to allow to insert parent_id in a new object ?
Thanks

**Comment by seuros** [comment]
I don't think this is possible out of the box.

**Comment by thooams** [comment]
I solved my problem by inserting a uuid instead of an id.
You can take this example: https://github.com/mceachen/closure_tree/blob/5ad0d58a0ee3744c2c80dab3156802c778fce566/spec/db/models.rb#L15

**Comment by mceachen** [comment]
I'd fairly strongly advise against MTI. I actually applied it
prototypically whole building Twitter's ads system (4 years ago!), and it
made recursion queries enormously convoluted.

In your example, pattern off of inodes and add an fk link to more metadata
to keep the base table columns mostly generally useful.

MTI is not supported by closure_tree.

**Comment by thooams** [comment]
Ok thanks your advice :+1:
