### ISSUE TITLE
update_all not working as expected

### ISSUE THREAD

**Issue by MichaelSp** [mceachen/closure_tree#197]
When I run this code: 

`Category.where(name: child_name).update_all parent_id: parent.id`

the `category_hierarchies`-table is not populated correctly. Thus queries like `category.ancestors.pluck(&:name)` are always empty even though `category.parent_id` is right.

**Comment by mceachen** [comment]
Not to be flippant, but don't do that.

If you run .update_all, you're changing an unknown set of rows with no
changed-entry callback. I don't see how that could ever be supported.
