### ISSUE TITLE
How can I implemet grouped_collection_select

### ISSUE THREAD

**Issue by erolg** [mceachen/closure_tree#198]
I have Location model which is use closure_tree.

I want to Implement [grouped_collection_select](http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html) for my form. There is just root nodes and their children in my model.

I want to implement something like this, 
```html
<select name="locations">
  <optgroup label="Office">
    <option value="3">Office Table 1</option>
    <option value="4">Office Table 2</option>
  </optgroup>
  <optgroup label="Lab">
    <option value="5">Another Door 1</option>
    <option value="6">Another Door 2</option>
    <option value="7">Another Door 3</option>
    <option value="8">Another Door 4</option>
    <option value="11">Another Door 5</option>
  </optgroup>
  ⋮
</select>
```

**Comment by dmitry** [comment]
It's just simple as this: http://api.rubyonrails.org/classes/ActionView/Helpers/FormOptionsHelper.html#method-i-grouped_options_for_select

Nothing really difficult to implement. I'd say this issue should be closed, as it's not really related to  the closure_tree.
