### ISSUE TITLE
Add dependent: restrict_with_exception and dependent: restrict_with_error options

### ISSUE THREAD

**Issue by shvetsovdm** [mceachen/closure_tree#201]
Since the 4.1 version Rails has options `restrict_with_error` and `restrict_with_exception` for the `has_many` associations. It will be great to have this options in Closure Tree.

**Comment by mceachen** [comment]
It wouldn't be hard to pass those options through (and straightforward to test)—I'd be more than happy to accept your pull request!

**Comment by shvetsovdm** [comment]
Thanks. I'll try to do that.

**Comment by tonyday** [comment]
I have tried the following in my model and so far it seems to work for me (Rails 4.2 and ActiveAdmin):

`has_closure_tree order: 'name', dependent: :restrict_with_error`

Based on my nooby reading of the code, the dependent option simply gets passed to ActiveRecord so no code change (in closure_tree) required.

**Comment by shvetsovdm** [comment]
@tonyday absolutely
