### ISSUE TITLE
Question: Easy way to solve N+1?

### ISSUE THREAD

**Issue by blimey85** [mceachen/closure_tree#208]
I was going to post this on StackOverflow but since it's rather specific to this gem, I thought I'd ask here first. Hopefully that's ok. I have closure_tree working quite nicely for a comments system. If I go to a status, all comments on that status will show and that part works great. If I go to the news feed, I show 10 statuses at a time, and then it calls hash_tree 10 times which means 10 database hits.

Is it possible using joins and includes to move this into my initial query for statuses? Something like: 

`@statuses = Status.where('something here').joins('sql for closure_tree).includes(:comments)`

If it is possible I can work out what code I need to do it, I'm just not sure if it's possible. The end result is I'm wanting to call status.comments.hash_tree, or something similar, and have it via the collection.

**Comment by smedstadc** [comment]
I know this is an old issue, but this may help someone else.

You should be able to include one of the scopes listed here: https://github.com/mceachen/closure_tree#instance-methods

If ActiveRecord complains about undefined tables, you might need to add `.references(:modelname_hierarchies)`.

It pays to RTFM 😄
