### ISSUE TITLE
Infinite recursion when bypassing validation with update_attribute

### ISSUE THREAD

**Issue by nbouscal** [mceachen/closure_tree#210]
The validation that prevents adding an ancestor as a descendant doesn't run when using the `update_attribute` method to set a model's parent. This then leads to an infinite recursion and a `SystemStackError`. You can reproduce by just calling `tag.update_attribute(:parent, tag)`.

**Comment by mceachen** [comment]
Thanks for the report.

update_attribute isn't one of the documented methods of setting parentage.
Do you think we should add this to the documentation as a way it *doesn't*
work?

**Comment by nbouscal** [comment]
Yeah, I think that would be helpful.
