### ISSUE TITLE
Is there a way to limit the depth of a tree on create ?

### ISSUE THREAD

**Issue by nicolas-besnard** [mceachen/closure_tree#212]

**Comment by mceachen** [comment]
Do you mean like a depth limit validation?

**Comment by nicolas-besnard** [comment]
Yes
On Tue, 10 May 2016 at 21:20, Matthew McEachen <notifications@github.com>
wrote:

> Do you mean like a depth limit validation?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mceachen/closure_tree/issues/212#issuecomment-218262231>
>
-- 
Nicolas

**Comment by mceachen** [comment]
No, and I don't think it would be advisable. That validation belongs in
your model, not in this storage implementation.

This would be terribly errorprone when it came to moving subtrees, for
example.
