### ISSUE TITLE
Setting the parent to itself causes an infinite loop of SQL queries

### ISSUE THREAD

**Issue by itay-grudev** [mceachen/closure_tree#219]
Even though this is not standard usage of the library it would be nice if it handles this corner case internally.

**Comment by mceachen** [comment]
Pull requests are welcome!

**Comment by mceachen** [comment]
Note that in [_ct_validate](https://github.com/mceachen/closure_tree/blob/8089f887540aad58f3ae828036e26614427df241/lib/closure_tree/hierarchy_maintenance.rb#L22) there is a validation to prevent this, and there are unit tests that exercise that code.
