### ISSUE TITLE
hash_tree not using STI scope on Rails 5

### ISSUE THREAD

**Issue by aaronrussell** [mceachen/closure_tree#220]
Testing one of my apps for Rails 5, and have noticed `hash_tree` doesn't use the STI scope of the calling class. I can't pinpoint exactly where the issue is in the code, but can confirm the following SQL statements.

When calling `Page.hash_tree`

### Rails 4.2

```sql
SELECT "nodes".* FROM "nodes" INNER JOIN (
  SELECT descendant_id, MAX(generations) as depth
  FROM "node_hierarchies"
  GROUP BY descendant_id
  
) AS generation_depth
  ON "noes".id = generation_depth.descendant_id
  WHERE "nodes"."type" IN ('Page')
  ORDER BY generation_depth.depth, sort_order
```

### Rails 5

```sql
SELECT "nodes".* FROM "nodes" INNER JOIN (
  SELECT descendant_id, MAX(generations) as depth
  FROM "node_hierarchies"
  GROUP BY descendant_id
  
) AS generation_depth
  ON "nodes".id = generation_depth.descendant_id
  ORDER BY generation_depth.depth, sort_order
```

Notice that rails 5 does't include the `WHERE "nodes"."type" IN ('Page')` condition.

**Comment by aaronrussell** [comment]
I can add a bit more info to this. It is not just the STI scope that is affected - it is any scope.
eg:

    Page.where(status: 'published').hash_tree

Generates the same query above, ignoring the where condition.

**Comment by mceachen** [comment]
AFAIK closure tree and rails 5 hasn't been verified by anyone yet.

Given how much work had to be done from rails 3 to 4, it's not surprising
rails 5 has broken fairly basic assumptions made by this library as well.

The first step would be to add a gemfiles/activerecord-5.0.0rc1.gemfile and
see what's breaking.

The second step is to figure out what needs to change in the gem to make
rails 5 happy.

The third step is to figure out how to do that simultaneously with rails 4
to make both happy.

The fourth step is whiskey.

**Comment by aaronrussell** [comment]
closure_tree is a core part of my project - https://github.com/pushtype/push_type - and I'm kind of optimistic not too much is broken in rails 5 (i may regret saying that :))

The only closure_tree related issues I've found is this one, and the issue fixed in #209.

If you like I can try and help you with your first step (get a form with a rails5 gemfile), so I can at let you know the lay of the land. I'm not sure I'll be able to help too much with 2 & 3, but can definitely help you with 4!

**Comment by mceachen** [comment]
Any help is greatly appreciated! With RC1 out for a month already, the
final release is imminent.

**Comment by aaronrussell** [comment]
I've created a rails-5 fork with new gemset: https://github.com/aaronrussell/closure_tree/tree/rails-5

All of your tests pass with activerecord 5. I'm not sure if that's good thing or a worrying thing 😟 . Next week I'll try and add a failing test for this specific issue. Hopefully though, this upgrade won't cause too many nightmares.

**Comment by mceachen** [comment]
NICE
