### ISSUE TITLE
Request new release

### ISSUE THREAD

**Issue by aaronrussell** [mceachen/closure_tree#225]
Could I request a new gem release please?

Specifically I'm waiting for #209 and #221 to be packaged in a gem so I can get a rails-5 ready version of https://github.com/pushtype/push_type out.

Apologies for raising this is an issue. If there's anything holding up a new version, let me know if there's anything I can help with.

**Comment by mceachen** [comment]
I won't be able to push until end of next week. Sorry for the delay.

**Comment by aaronrussell** [comment]
No worries. That helps to know 👍

**Comment by seuros** [comment]
A release candidate is being tested https://github.com/mceachen/closure_tree/pull/226

**Comment by mceachen** [comment]
just released 6.1.0, thanks for your PRs!
