### ISSUE TITLE
Duplication of entries when find_or_create_by_path is run concurrently 

### ISSUE THREAD

**Issue by DuaneCompton** [mceachen/closure_tree#227]
I am seeing duplicate entries in our database sporadically using Postgres 9.4.4, Rails 4.2.6, closure tree 6.0 and using the your advisory lock gem 3.0.0. We have multiple workers that are calling find_or_create_by_path with duplicate data.

Running the following script from two rails consoles sometimes results in this behavior as well.
`Topic.transaction do`
     `(0..500).each { Tag.find_or_create_by_path(["grandparent", "parent", "child"]) } `
`end`

I was wondering if wrapping the call in the transaction block could somehow be creating this issue or if the find_or_create_by_path is bugged? 

Any help is appreciated. Thanks!

**Comment by mceachen** [comment]
Transaction boundaries in MySQL actually block concurrent access. PG
supports MVCC, though, so if the advisory lock is somehow not working,
dupes would be expected.

Can you add a debug statement to see what named mutex the different
consoles are using? The string must match.

**Comment by DuaneCompton** [comment]
If I am reading this correctly, the locks do appear differ: 
> 
D, [2016-08-04T15:16:54.411922 #12307] DEBUG -- :    (0.2ms)  BEGIN
W, [2016-08-04T15:16:54.412477 #12307]  WARN -- :   ↳ concurrency_test.rb:1:in `<top (required)>'
>
D, [2016-08-04T15:16:54.526826 #12307] DEBUG -- :   Tag Load (1.2ms)  SELECT  "tags".* FROM "tags" INNER JOIN "tags" AS p0
             ON p0."id" =
"tags"."parent_id" INNER JOIN "tags" AS p1
             ON p1."id" =
"p0"."parent_id" INNER JOIN "tags" AS p2
             ON p2."id" =
"p1"."parent_id" WHERE "tags"."name" = $1 AND "p0"."name" = 'Child' AND "p1"."name" = 'Parent' AND "p2"."name" = 'Grandparent' AND "p2"."parent_id" IS NULL  ORDER BY "tags"."id" ASC LIMIT 1  [["name", "Baby"]]
W, [2016-08-04T15:16:54.528401 #12307]  WARN -- :   ↳ /usr/local/bundle/gems/closure_tree-6.0.0/lib/closure_tree/finders.rb:131:in `find_by_path'
>
D, [2016-08-04T15:16:54.671454 #12307] DEBUG -- :    (0.3ms)  SELECT **pg_try_advisory_lock(1814493058,0) AS t7bffa1783532c3e0bbb7929b9f16419b**
W, [2016-08-04T15:16:54.671647 #12307]  WARN -- :   ↳ /usr/local/bundle/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/postgresql.rb:14:in `execute_successful?' 

and
>
D, [2016-08-04T15:16:26.062125 #12274] DEBUG -- :    (0.3ms)  BEGIN
W, [2016-08-04T15:16:26.062554 #12274]  WARN -- :   ↳ concurrency_test.rb:1:in `<top (required)>'
>
D, [2016-08-04T15:16:26.089468 #12274] DEBUG -- :   Tag Load (1.1ms)  SELECT  "tags".* FROM "tags" INNER JOIN "tags" AS p0
             ON p0."id" =
"tags"."parent_id" INNER JOIN "tags" AS p1
             ON p1."id" =
"p0"."parent_id" INNER JOIN "tags" AS p2
             ON p2."id" =
"p1"."parent_id" WHERE "tags"."name" = $1 AND "p0"."name" = 'Child' AND "p1"."name" = 'Parent' AND "p2"."name" = 'Grandparent' AND "p2"."parent_id" IS NULL  ORDER BY "tags"."id" ASC LIMIT 1  [["name", "Baby"]]
W, [2016-08-04T15:16:26.089722 #12274]  WARN -- :   ↳ /usr/local/bundle/gems/closure_tree-6.0.0/lib/closure_tree/finders.rb:131:in `find_by_path'
>
D, [2016-08-04T15:16:26.114383 #12274] DEBUG -- :    (0.4ms)  SELECT **pg_try_advisory_lock(1814493058,0) AS t260c198a0e803bb83c56d410dba911d4**
W, [2016-08-04T15:16:26.114604 #12274]  WARN -- :   ↳ /usr/local/bundle/gems/with_advisory_lock-3.0.0/lib/with_advisory_lock/postgresql.rb:14:in `execute_successful?'

**Comment by mceachen** [comment]
They are both trying to acquire lock *1814493058*.

**Comment by mceachen** [comment]
Did you resolve the issue?
