### ISSUE TITLE
Second hierarchy for the same model

### ISSUE THREAD

**Issue by zedalaye** [mceachen/closure_tree#235]
While it looks feasible using has_closure_tree options (parent_column_name, hierarchy_class_name...) it seems not possible to declare two hierachies for the same model because all generated methods (children, for instance) will share the same name.

Do you have a clue on how to create a second hierachy for the same model ?

**Comment by mceachen** [comment]
This would require foreign keys whose constraint is conditional on other attributes of a given row. AFAIK this is not supported by any RDBMS.

If it's a different forest of nodes, use a different class.
