### ISSUE TITLE
index on ancestor_id

### ISSUE THREAD

**Issue by yijia-zhan** [mceachen/closure_tree#243]
It looks like there's `closure_tree` adds an index on `descendant_id` and another compound unique index on `ancestor_id`, `descendant_id` and `generation`. 

Is there any particular reason why there wasn't an index on `ancestor_id`? There will be a `where ancestor.id = ?` filter clause in the SQL generated for any `.descendants` look up, right?

**Comment by mceachen** [comment]
Read up on compound indexes.
http://dev.mysql.com/doc/refman/5.7/en/multiple-column-indexes.html
