### ISSUE TITLE
Closure_tree is too complex, I designed another simple solution

### ISSUE THREAD

**Issue by drinkjava2** [mceachen/closure_tree#247]
Could you take a look of this:  
[https://github.com/drinkjava2/Multiple-Columns-Tree](https://github.com/drinkjava2/Multiple-Columns-Tree)
Use 2 extra columns: (sorted) line and depth, will easily do SQL query/delete/insert operations for child/sibling/parent nodes.

**Comment by mceachen** [comment]
In the future, if you're asking for an algorithm review, you might want to write in the language of the reviewer. I'm assuming that the [google translation](https://translate.googleusercontent.com/translate_c?act=url&depth=1&hl=en&ie=UTF8&prev=_t&rurl=translate.google.com&sl=zh-CN&sp=nmt4&tl=en&u=https://github.com/drinkjava2/Multiple-Columns-Tree&usg=ALkJrhiAEbqdKhoLzcPrBqBb4fGEkmPh8Q) is ok.

If you look at the simple parent-child mapping and hierarchical maintenance in this gem, there isn't that much code. 

The complexity in this library is from surrounding functionality, like deterministic ordering management, preorder and postorder support, and concurrency locking.

With respect to your approach, I don't get it--without a column holding `parent`, you can't easily ascend or descend your tree, and there isn't a way to index your schema to support 1-query hierarchy selects.

**Comment by drinkjava2** [comment]
My mistake, I think I can make the translate( to English) before everyone see it, and I just uploaded the English version few minutes ago,  but apparently I'm wrong as you already go to my site.
As I said in English translated version, the shortage of "Sorted-Unlimited-Depth-Tree" method is hard to move nodes tree, (you already notice of that) except that, it's a good tree solution for many applications.
"line" is a sorted number indicate the order of the item, each time when insert or move nodes, need do a "re-order" work, usually this is protected in a database transaction. An other solution is sorted them in memory and flush to database at one batch(use SQL batch function).
