### ISSUE TITLE
Reverse generation order

### ISSUE THREAD

**Issue by yijia-zhan** [mceachen/closure_tree#248]
The descendants look ups are done in [ascending generation orders](https://github.com/mceachen/closure_tree/blob/2449029ecb7f287198154057bae88a912bfb5352/lib/closure_tree/model.rb#L31-L49), is there an easy way to make them return in reverse generation order? 

Basically, in my use case, I need to get the lowest level nodes in the tree, then a level up, ... and finally the root. I guess another way is to use `.find_all_by_generation` by looping through the levels. Is there a way to quickly determine the total depth of a tree?

**Comment by yijia-zhan** [comment]
I think I can reverse the generation order in memory `self_and_descendants.reverse`, but is it possible to sort it in database?

**Comment by mceachen** [comment]
to find the max depth of the tree, take a look [here](https://github.com/mceachen/closure_tree/blob/master/lib/closure_tree/numeric_deterministic_ordering.rb). 

To reverse the generation order, you'll want to append "desc" to the ORDER BY created by `_ct_sum_order_by`.
