### ISSUE TITLE
prepend_child throws an exception in case of invalid object

### ISSUE THREAD

**Issue by amitsaxena** [mceachen/closure_tree#249]
`prepend_child` works fine if I try to save a valid item, but it throws an exception in case of validation errors. The behaviour should be similar to that of `append_child` which returns the object along with validation errors when someone tries to add a child. See below:
```
root = List.find(10)
child = List.new(:name => "test_bug")
child.valid?
=> false
root.prepend_child(child)
=> ActiveRecord::RecordNotFound: Couldn't find List without an ID
```

```
root.append_child(child)
=> #<List id: nil, ....>
child.valid?
=> false
child.errors
=>  #<ActiveModel::Errors:0x007f9c7a2add70...
```

**Comment by mceachen** [comment]
Thanks for the PR! Merged into v6.3.0
