### ISSUE TITLE
Does closure tree work with an Entity relationship model with multiple non-polymorphic models?

### ISSUE THREAD

**Issue by diogocsc** [mceachen/closure_tree#255]
I have came across closure tree some days ago while looking for some way of displaying a set of records as tree.

Mainly I have a structure that is something like:
company -> process -> activity -> sub-activity -> pollution-origin-> sub-pollution-origin.

For each of them I created a model class, which is to serve as a template for each, and they all reference their parent record, as indicated by the arrows above (parent -> child)

Now I am wanting some way of mapping the full configuration, and adding or removing nodes easily.
I wonder if this can be done with closure tree without creating a polymorphic structure.

**Comment by mceachen** [comment]
Polymorphic models are supported ([rtfm](https://github.com/mceachen/closure_tree#polymorphic-hierarchies-with-sti)), but wholly different models are not.

The fundamental issue here is that you're mixing primary keys from multiple tables. Without tupling the keys with an identifier, it isn't clear what table the key points to. It also makes it impossible to use foreign key constraints.

I don't know what your typical access patterns look like, nor how heavyweight these models are, but you could leverage STI and at the same time move the bulk of fields into one-to-one "helper" models that can be eagerly loaded.
