### ISSUE TITLE
closure generators on new app

### ISSUE THREAD

**Issue by enneid** [mceachen/closure_tree#256]
Currently when i want to make  rails g closure_tree:migration on new solution (without init migrations) i will get set of errors (that refered thus model must exists, table must exists). 
Is it really needed that *generator* to depend on existing tables? shouldn;t be database and model agnostic?

**Comment by mceachen** [comment]
I'm surprised that you're getting an error. Our generator tests certainly start from an empty database. Perhaps if you look at how those tests are set up, and compare that with your setup, you'll see a difference?
