### ISSUE TITLE
Recommendation for a JS implementation

### ISSUE THREAD

**Issue by dinshaw** [mceachen/closure_tree#257]
Amazing lib, thank you for you work.
I'm passing small trees as a hash to the browser.
Would you have any recommendations for libs, or strategies, for walking the tree with JS?
Thanks!

**Comment by dinshaw** [comment]
I ended up using this guy: http://jnuno.com/tree-model-js/
Pretty easy to implement from scratch. My use case is a survey where both questions and answers are nodes, so i needed some custom traversing. But otherwise way easier than i thought.

**Comment by mceachen** [comment]
Thanks for the update!
