### ISSUE TITLE
Change to attribute_change in Rails 5.1

### ISSUE THREAD

**Issue by cpence** [mceachen/closure_tree#261]
Rails 5.1rc1 introduces a new extensive set of deprecation warnings that seem to be arising from closure_tree.

> DEPRECATION WARNING: The behavior of `attribute_change` inside of after callbacks will be changing in the next version of Rails. The new return value will reflect the behavior of calling the method after `save` returned (e.g. the opposite of what it returns now). To maintain the current behavior, use `saved_change_to_attribute` instead. (called from block in ...)

Elsewhere the same message appears for `attribute_changed?`.

As far as I can tell, that's all coming from [this line in the code,](https://github.com/mceachen/closure_tree/blob/master/lib/closure_tree/numeric_deterministic_ordering.rb#L13) in the numeric ordering module.

**Comment by mceachen** [comment]
Thanks for the heads up. PRs are very welcome! (I won't be able to get to
this for at least a couple weeks).

**Comment by cpence** [comment]
Will see what I can put together!

**Comment by cpence** [comment]
Just opened a PR for the deprecation warnings. Still some test failures on AR5.1, at least on my machine, that I don't know how to fix. But we can move discussion over to the PR.
