### ISSUE TITLE
self_and_descendant_ids does not cache associations?

### ISSUE THREAD

**Issue by FX-HAO** [mceachen/closure_tree#266]
`self_and_descendant` seems to work, but `self_and_descendant_ids` take a database read every time.

I use it many times in cancancan, so this obviously can lead to serious performance issues.

**Comment by mceachen** [comment]
That's surprising to me, given that `self_and_descendant_ids` just delegates to the (presumably cached) `self_and_descendants` relation. 

Can you post sample code? It works for me.

**Comment by FX-HAO** [comment]
I noticed that `pluck` refetch `ActiveRecord_Associations_CollectionProxy` from database every time, is it normal?

**Comment by FX-HAO** [comment]
I got it, `pluck` goes to DB every time. So i changed it to `self_and_descendants.map(&:id)`.

**Comment by mceachen** [comment]
Nice! I'm sure you're not the only one using that method. Would you be
willing to make a PR with your fix?

Thanks!

**Comment by FX-HAO** [comment]
It really depends on context. It's not a big problem with appropriate use.

### problem

	can :create, User, tree: {id: tree.self_and_descendant_ids}
	can :update, Post, tree: {id: tree.self_and_descendant_ids}

### workaround 1

	tree.self_and_descendants.map(&:id)
	tree.self_and_descendants.map(&:id)

### workaround 2

	tree_ids = tree.self_and_descendant_ids
	can :create, User, tree: {id: tree_ids}
	can :update, Post, tree: {id: tree_ids}

**Comment by FX-HAO** [comment]
And the problem should be fixed by Rails 5. https://github.com/rails/rails/pull/25976
