### ISSUE TITLE
Eager loading children infinitely nested

### ISSUE THREAD

**Issue by Un3qual** [mceachen/closure_tree#267]
When I try to eager load children with 
```
@comments = Comment.where(commentable: find_commentable).where(parent_id: nil).includes(:children)
render json: @comments
```
It renders just fine, but bullet says
```
USE eager loading detected
  Comment => [:children]
  Add to your finder: :includes => [:children]
```
If I add this to when I render it
```
render json: @comments, include: ["children"]
```
Bullet stops whining, but it only loads one level deep.

If I change that to 
```
render json: @comments, include: ["children.**"]
```
It has all of the levels of nesting, but bullet tells me
```
USE eager loading detected
  Comment => [:children]
  Add to your finder: :includes => [:children]
```

**Comment by Un3qual** [comment]
Whoops. Typo on my end. Sorry ;(

**Comment by Un3qual** [comment]
Update:
It works if I chain includes like this:
```ruby
Comment.where(commentable: find_commentable).where(parent_id: nil).includes(:commenter).includes({children: [{children: [{children: [{children: [{children: [:children, :commenter]}, :commenter]}, :commenter]}, :commenter]}, :commenter]}).includes(:commenter)
```
But that will stop working when the nesting gets deeper than the number of nests I have inside the includes. That's also just a bad solution.

**Comment by Un3qual** [comment]
Fixed by adding 
```ruby
default_scope { includes(:children).includes(:commenter) }
```
to the Comment model.

**Comment by mceachen** [comment]
I'd be really careful about `default_scope`. And by "careful," I mean "most likely you have broken large swaths of functionality in closure_tree, I hope you have tests and have backed up your database."
